server:
  port: ${APPLICATION_SERVER_PORT:8089}
spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${DDL_AUTO}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}